###############################################################################
#                           Common                                            #
###############################################################################
[common]
   version = "0.0.1" 
   is_debug = false 
   log_level = "info"
   log_path = "./out.log"

[server]
   addr = "0.0.0.0:8800"
   dir = "./dir/"

[python]
   lib_dir = "libpython"